services:
  simple-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      platforms:
        - linux/amd64  # AMD64 for deployment compatibility
        - linux/arm64  # ARM64 for Apple Silicon compatibility and local development
    image: simple-http-api:latest
    container_name: simple-http-api
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          cpus: '1.0'
        limits:
          cpus: '3.0'
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - simple-api-network

networks:
  simple-api-network:
    driver: bridge 