version: '3.8'

services:
  simple-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: simple-http-api
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - simple-api-network

networks:
  simple-api-network:
    driver: bridge 